version: '3'

services:
  php:
    build: './docker/php'
    volumes:
      - './app:/var/www/html'
#      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
    container_name: php


  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    container_name: nginx


  db:
    image: mysql
    environment:
      MYSQL_DATABASE: olxPrice
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './docker/db/mysql:/var/lib/mysql'
    container_name: db


  db_test:
    image: mysql
    container_name: db_test
    environment:
      MYSQL_DATABASE: test_database
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - './docker/db/test_db:/var/lib/mysql'
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    container_name: phpmyadmin
