version: '3'

services:
  php:
    build: './docker/php'
    volumes:
      - './app:/var/www/html'
    container_name: php


  nginx:
    image: nginx:1.27.1
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    container_name: nginx

  db:
    image: mysql:9.0.1
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - './docker/db/mysql:/var/lib/mysql'
    container_name: db

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8000:80
    container_name: phpmyadmin
