version: '3'

services:
  php:
    build: './docker/php'
    volumes:
      - './app:/var/www/html'
      - './docker/php/php.ini:/usr/local/etc/php/php.ini'
    container_name: php


  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    container_name: nginx


  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/db/mysql:/var/lib/mysql'
    container_name: db

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    container_name: phpmyadmin
